[project]
name = "tlagen"
version = "0.1.0"
description = ""
authors = [
    {name = "David Yue",email = "davidyue5819@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyparsing (>=3.3.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
