/*
 * missing_sass_kernels.cu
 *
 * CUDA kernels designed to compile down to the SASS instructions listed in
 * src/missing_sass.txt. Compile for the appropriate target architecture:
 *
 *   nvcc -arch=sm_100a -o missing_sass_kernels missing_sass_kernels.cu
 *   cuobjdump -sass missing_sass_kernels | grep -E "VIADD|VIADDMNMX|F2FP|F2I|HFMA2|R2UR|S2UR|UTCATOMSWS"
 *
 * IMPORTANT: The exact SASS generated depends on nvcc version and target arch.
 * These kernels are best-effort attempts to elicit the target instructions.
 * Some instructions (S2UR with SR_C, UTCATOMSWS, R2UR.OR) are generated by
 * internal compiler machinery or CUTLASS/CuTe and cannot be reliably produced
 * from plain CUDA source.
 *
 * Confidence levels per instruction:
 *   HIGH:    F2I.FTZ.U32.TRUNC, HFMA2, F2FP.BF16
 *   MEDIUM:  VIADD, VIADDMNMX.U32, R2UR (simple form), S2UR (CTAID form)
 *   LOW:     R2UR.OR, S2UR (SR_C form), UTCATOMSWS
 */

#include <cuda_fp16.h>
#include <cuda_bf16.h>


/* -----------------------------------------------------------------------
 * Target: F2FP.SATFINITE.BF16.*
 *
 * Float-to-BF16 conversion with saturation (clamp infinities to max
 * representable BF16). The __float2bfloat16 intrinsic should emit this.
 * ----------------------------------------------------------------------- */
__global__ void kernel_f2fp_bf16(const float* __restrict__ in,
                                 __nv_bfloat16* __restrict__ out,
                                 int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        /* float -> bfloat16 conversion with round-to-nearest and saturation */
        out[idx] = __float2bfloat16_rn(in[idx]);
    }
}


/* -----------------------------------------------------------------------
 * Target: F2I.FTZ.U32.TRUNC.NTZ
 *
 * Float-to-unsigned-integer conversion with truncation (round toward zero)
 * and flush-to-zero for denormals. A simple (unsigned int) cast on a float
 * should produce this.
 * ----------------------------------------------------------------------- */
__global__ void kernel_f2i_u32(const float* __restrict__ in,
                               unsigned int* __restrict__ out,
                               int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        float val = in[idx];
        /* __float2uint_rz: explicit round-toward-zero, flush-to-zero */
        out[idx] = __float2uint_rz(val);
    }
}


/* -----------------------------------------------------------------------
 * Target: HFMA2
 *
 * Packed half-precision fused multiply-add on two FP16 values packed in a
 * 32-bit register. The __hfma2 intrinsic operates on __half2 vectors.
 *
 * In the unsupported log, HFMA2 appeared as:
 *   HFMA2 R9, RZ, RZ, 0, 5.96e-08
 * which is: R9 = RZ * RZ + <small_constant> = 0 + epsilon
 * i.e., loading a small FP16 constant. But the general case below should
 * also emit HFMA2 for the actual multiply-add.
 * ----------------------------------------------------------------------- */
__global__ void kernel_hfma2(const __half2* __restrict__ a,
                             const __half2* __restrict__ b,
                             const __half2* __restrict__ c,
                             __half2* __restrict__ out,
                             int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        /* Packed FP16 fused multiply-add: out = a * b + c */
        out[idx] = __hfma2(a[idx], b[idx], c[idx]);
    }
}

/* Also: loading a small half2 constant (the pattern seen in real kernels) */
__global__ void kernel_hfma2_const(__half2* __restrict__ out, int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        /* This pattern (0 * 0 + eps) is how the compiler loads small FP16
           constants — it should emit HFMA2 Rx, RZ, RZ, 0, <imm> */
        out[idx] = __float2half2_rn(5.9604644775390625e-08f);
    }
}


/* -----------------------------------------------------------------------
 * Target: VIADD
 *
 * On Blackwell (sm_100a), the compiler often emits VIADD for simple 32-bit
 * integer additions, especially for loop counters and small-constant adds.
 * The "V" prefix historically means video/SIMD but on recent architectures
 * it appears to be used for scalar integer adds as well.
 *
 * Patterns seen in real SASS:
 *   VIADD R11, R11, 0x1          (increment by 1)
 *   VIADD R5, R5, 0xffffffe      (add -2, i.e., subtract 2)
 *   VIADD R5, R6, UR11           (add uniform register)
 *   VIADD R4, R2, 0xffffff00     (mask low 8 bits via add)
 * ----------------------------------------------------------------------- */
__global__ void kernel_viadd(int* __restrict__ data, int n, int stride)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        int val = data[idx];

        /* Simple increments — likely VIADD Rx, Rx, 0x1 */
        val = val + 1;

        /* Add a runtime value — likely VIADD Rx, Rx, Ry */
        val = val + stride;

        /* Subtract via add of negative — likely VIADD Rx, Rx, 0xfffffffe */
        val = val - 2;

        /* Mask pattern — likely VIADD Rx, Rx, 0xffffff00 */
        val = val & 0xffffff00;

        data[idx] = val;
    }
}


/* -----------------------------------------------------------------------
 * Target: VIADDMNMX.U32
 *
 * Integer add combined with min/max clamping. The pattern seen:
 *   VIADDMNMX.U32 R2, R0, R5, 0x2, PT
 * suggests: R2 = clamp(R0 + R5, ..., 2) or min(R0 + R5, 2) with PT
 * selecting min vs max. Using min/max on unsigned integers after addition
 * should trigger this.
 * ----------------------------------------------------------------------- */
__global__ void kernel_viaddmnmx(unsigned int* __restrict__ data, int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        unsigned int a = data[idx];
        unsigned int b = data[idx + n];

        /* Clamped add: min(a + b, 2) — should emit VIADDMNMX.U32 */
        unsigned int sum = a + b;
        unsigned int clamped = min(sum, 2u);

        data[idx] = clamped;
    }
}

/* Alternative: clamp to a range (add then min then max) */
__global__ void kernel_viaddmnmx_clamp(unsigned int* __restrict__ data,
                                       unsigned int lo,
                                       unsigned int hi,
                                       int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        unsigned int val = data[idx] + data[idx + n];
        val = max(val, lo);
        val = min(val, hi);
        data[idx] = val;
    }
}


/* -----------------------------------------------------------------------
 * Target: R2UR (simple form)
 *
 * Move a per-thread register value into a uniform register. The compiler
 * generates this when it can prove the value is warp-uniform and needs it
 * in a uniform register for subsequent uniform operations (ULEA, UIMAD).
 *
 * Pattern seen:  R2UR UR18, R4
 *
 * Using blockIdx (uniform across a warp) in arithmetic that the compiler
 * can't fold at compile time should force a R2UR.
 * ----------------------------------------------------------------------- */
__global__ void kernel_r2ur(const int* __restrict__ in,
                            int* __restrict__ out,
                            int n)
{
    /* blockIdx.x is warp-uniform. Load it into a register, then use it
       in uniform address computation — compiler should emit R2UR. */
    int block_offset = blockIdx.x * blockDim.x;
    int tid = threadIdx.x;

    /* Force the uniform value through a non-trivial path so the compiler
       doesn't just use S2UR directly. */
    int uniform_val = block_offset + blockDim.x;
    if (tid < n) {
        /* Use uniform_val in address computation — triggers ULEA/UIMAD
           which requires the value in a uniform register, forcing R2UR. */
        out[tid] = in[tid + uniform_val];
    }
}


/* -----------------------------------------------------------------------
 * Target: S2UR
 *
 * Move a special register to a uniform register. The simple form:
 *   S2UR UR10, SR_CTAID.Z
 * comes from reading blockIdx.z into a uniform register context.
 *
 * The 4-operand form with SR_C:
 *   S2UR UR9, SR_C, C, I
 * reads the convergence state register — this is compiler-internal for
 * warp divergence tracking and cannot be reliably generated from CUDA.
 * ----------------------------------------------------------------------- */
__global__ void kernel_s2ur(int* __restrict__ out, int n)
{
    /* blockIdx is uniform across the warp. Using all three components
       in uniform arithmetic should emit S2UR for SR_CTAID.X/Y/Z. */
    int idx = threadIdx.x;
    if (idx < n) {
        int block_linear = blockIdx.x
                         + blockIdx.y * gridDim.x
                         + blockIdx.z * gridDim.x * gridDim.y;
        out[idx] = block_linear + idx;
    }
}


/* -----------------------------------------------------------------------
 * Target: R2UR.OR
 *
 * Likely a warp-level OR-reduction into a uniform register. This might
 * come from __ballot_sync or similar warp-vote intrinsics where the
 * result needs to be in a uniform register.
 *
 * LOW CONFIDENCE that this CUDA code will emit R2UR.OR — the compiler
 * may choose different instruction sequences.
 * ----------------------------------------------------------------------- */
__global__ void kernel_r2ur_or(const int* __restrict__ in,
                               unsigned int* __restrict__ out,
                               int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        /* __ballot_sync returns a warp-uniform mask — the compiler may
           use R2UR.OR to accumulate per-thread predicates into UR. */
        int val = in[idx];
        unsigned int mask = __ballot_sync(0xffffffff, val > 0);

        /* Use the uniform result in further computation */
        if (threadIdx.x == 0) {
            out[blockIdx.x] = mask;
        }
    }
}


/* -----------------------------------------------------------------------
 * Target: UTCATOMSWS.FIND_AND_SET.ALIGN
 *
 * This is a Blackwell warp-specialization instruction. It atomically
 * finds and sets a bit in a thread-context scheduling structure. This is
 * generated by CUTLASS/CuTe's warp specialization runtime, not by plain
 * CUDA code.
 *
 * NO CUDA SOURCE can reliably emit this instruction. It requires the
 * CUTLASS warp-specialization infrastructure. Included here only for
 * documentation completeness.
 *
 * To obtain SASS containing UTCATOMSWS, compile a CuTe DSL kernel that
 * uses warp specialization (e.g., the FMHA or GEMM examples in the
 * regalloc-dataset/cutedsl/ directory).
 * ----------------------------------------------------------------------- */


/* -----------------------------------------------------------------------
 * Target: F2I.FTZ.U32.TRUNC.NTZ  (alternative patterns)
 *
 * Additional patterns that may trigger F2I with different modifiers.
 * ----------------------------------------------------------------------- */
__global__ void kernel_f2i_patterns(const float* __restrict__ in,
                                    unsigned int* __restrict__ out_trunc,
                                    int* __restrict__ out_signed,
                                    int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        float val = in[idx];

        /* Unsigned truncation toward zero */
        out_trunc[idx] = __float2uint_rz(val);

        /* Signed truncation (may emit F2I with different modifiers) */
        out_signed[idx] = __float2int_rz(val);
    }
}


/* -----------------------------------------------------------------------
 * Combined kernel exercising multiple target instructions
 *
 * This kernel mixes several patterns to maximize the chance of seeing
 * all target instructions in one compilation unit.
 * ----------------------------------------------------------------------- */
__global__ void kernel_combined(const float* __restrict__ float_in,
                                const __half2* __restrict__ half_in,
                                __nv_bfloat16* __restrict__ bf16_out,
                                unsigned int* __restrict__ uint_out,
                                __half2* __restrict__ half_out,
                                int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    /* S2UR: blockIdx into uniform register */
    int block_linear = blockIdx.x + blockIdx.y * gridDim.x
                     + blockIdx.z * gridDim.x * gridDim.y;

    if (idx < n) {
        /* F2FP.BF16: float -> bfloat16 */
        bf16_out[idx] = __float2bfloat16_rn(float_in[idx]);

        /* F2I: float -> uint */
        uint_out[idx] = __float2uint_rz(float_in[idx]);

        /* HFMA2: packed half FMA */
        __half2 a = half_in[idx];
        __half2 b = half_in[idx + n];
        __half2 c = __float2half2_rn(5.9604644775390625e-08f);
        half_out[idx] = __hfma2(a, b, c);

        /* VIADD: simple integer adds */
        int counter = idx + 1;
        counter = counter - 2;
        counter = counter + block_linear;

        /* VIADDMNMX: clamped unsigned add */
        unsigned int u = (unsigned int)counter;
        u = min(u + 3u, (unsigned int)n);

        uint_out[idx + n] = u;
    }
}
