"""
tla_codegen.py  --  Lift a sliced SASS CFG into a TLASassProcess.

Implements exactly the instruction semantics defined in sass/sass_insns.h.

Code generated by Claude Code
"""

from __future__ import annotations

from typing import Tuple

import re
from typing import Callable, Optional

from sass.parser import (
    Instruction,
    RegisterOp,
    ImmediateOp,
    LabelRef,
    MemAddrOp,
    ConstBankOp,
)
from sass.cfg import (
    CFG,
    BasicBlock,
    TerminatorKind,
    defs_of,
    uses_of,
)
from tla_module import (
    Expr,
    Add,
    IfThenElse,
    Literal,
    Unchanged,
    Not,
    Neg,
    Abs,
    Or,
    Min,
    Max,
    FunnelShr,
    Constant,
)
from tla_sass import TLASassProcess, TLASassThread

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_ALWAYS_TRUE_PREDS: frozenset[str] = frozenset({"PT", "UPT"})
_ZERO_REGS: frozenset[str] = frozenset({"RZ", "URZ", "SRZ"})
_DISCARD_DSTS: frozenset[str] = _ZERO_REGS | _ALWAYS_TRUE_PREDS


# ---------------------------------------------------------------------------
# Codegen
# ---------------------------------------------------------------------------


class SassCFGCodegen:
    def __init__(self) -> None:
        self.log: list[str] = []
        self._handlers: dict = {}
        self._build_handler_table()

    # ------------------------------------------------------------------
    # Handler table  (maps SASS mnemonics to handler methods)
    #
    # Only instructions with semantics defined in sass_insns.h are
    # included.  Everything else is logged as UNSUPPORTED.
    # ------------------------------------------------------------------

    def _build_handler_table(self) -> None:
        h = self._handlers

        # ---- S2R / S2UR / MOV / UMOV / CS2R / R2UR  (dst = src) ----
        for m in ("MOV", "UMOV", "S2R", "S2UR", "CS2R", "R2UR", "R2UR.OR"):
            h[m] = self._h_mov

        # ---- UP2UR  (uniform predicate to uniform register) ----
        h["UP2UR"] = self._h_up2ur

        # ---- IABS  (dst = abs(src)) ----
        h["IABS"] = self._h_iabs

        # ---- I2F.RP / MUFU.RCP / F2I.FTZ.U32.TRUNC.NTZ  (float, data-dep only) ----
        h["I2F.RP"] = self._h_fp_passthrough
        h["MUFU.RCP"] = self._h_fp_passthrough
        h["F2I.FTZ.U32.TRUNC.NTZ"] = self._h_fp_passthrough

        # ---- IADD3 / UIADD3 ----
        for m in ("IADD3", "UIADD3"):
            h[m] = self._h_iadd3

        # ---- IMAD and all variants ----
        for m in (
            "IMAD",
            "IMAD.U32",
            "IMAD.MOV",
            "IMAD.MOV.U32",
            "IMAD.IADD",
            "IMAD.IADD.U32",
            "IMAD.SHL",
            "IMAD.SHL.U32",
            "UIMAD",
            "UIMAD.U32",
        ):
            h[m] = self._h_imad

        # ---- IMAD.HI.U32  (read-modify-write) ----
        h["IMAD.HI.U32"] = self._h_imad_hi_u32

        # ---- Shift ----
        for m in ("SHF.R.U32.HI", "USHF.R.U32.HI"):
            h[m] = self._h_shf_r_u32_hi
        for m in ("SHF.R.S32.HI", "USHF.R.S32.HI"):
            h[m] = self._h_shf_r_s32_hi
        for m in ("SHF.L.U32", "USHF.L.U32"):
            h[m] = self._h_shf_l_u32

        # ---- Logical ----
        for m in ("LOP3.LUT", "ULOP3.LUT"):
            h[m] = self._h_lop3_lut
        h["PLOP3.LUT"] = self._h_plop3_lut
        for m in ("SEL", "USEL"):
            h[m] = self._h_sel

        # ---- Address computation ----
        h["LEA"] = self._h_lea
        for m in ("LEA.HI", "ULEA.HI"):
            h[m] = self._h_lea_hi
        for m in ("LEA.HI.SX32", "ULEA.HI.SX32"):
            h[m] = self._h_lea_hi_sx32

        # ---- IMNMX.U32 ----
        h["IMNMX.U32"] = self._h_imnmx_u32

        # ---- VIADD / VIMNMX / VIADDMNMX ----
        h["VIADD"] = self._h_viadd
        h["VIMNMX"] = self._h_vimnmx
        for m in ("VIADDMNMX", "VIADDMNMX.U32"):
            h[m] = self._h_viaddmnmx

        # ---- Predicate ----
        for pfx in ("ISETP", "UISETP"):
            h[f"{pfx}.LT.AND"] = self._h_isetp_lt_and
            h[f"{pfx}.LT.U32.AND"] = self._h_isetp_lt_and
            h[f"{pfx}.GT.AND"] = self._h_isetp_gt_and
            h[f"{pfx}.GT.U32.AND"] = self._h_isetp_gt_and
            h[f"{pfx}.GE.AND"] = self._h_isetp_ge_and
            h[f"{pfx}.GE.U32.AND"] = self._h_isetp_ge_and
            h[f"{pfx}.NE.AND"] = self._h_isetp_ne_and
            h[f"{pfx}.NE.U32.AND"] = self._h_isetp_ne_and
            h[f"{pfx}.EQ.AND"] = self._h_isetp_eq_and
            h[f"{pfx}.EQ.U32.AND"] = self._h_isetp_eq_and
            h[f"{pfx}.LE.AND"] = self._h_isetp_le_and
            h[f"{pfx}.LE.U32.AND"] = self._h_isetp_le_and
            h[f"{pfx}.GE.OR"] = self._h_isetp_ge_or
            h[f"{pfx}.GE.U32.OR"] = self._h_isetp_ge_or
        h["P2R"] = self._h_p2r

        # ---- Constant-bank loads (ULDC / LDC / LDCU) ----
        for m in ("ULDC", "LDC", "LDCU"):
            h[m] = self._h_uldc
        for m in ("ULDC.64", "LDC.64", "LDCU.64"):
            h[m] = self._h_uldc_64

        # ---- Sync phase check (predicate = TRUE) ----
        for m in ("SYNCS.PHASECHK.TRANS64.TRYWAIT", "SYNCS.PHASECHK.TRANS64"):
            h[m] = self._h_syncs_phasechk

        # ---- USETMAXREG: CTA-pool register allocation (guarded) ----
        h["USETMAXREG.TRY_ALLOC.CTAPOOL"] = self._h_usetmaxnre_inc
        h["USETMAXREG.DEALLOC.CTAPOOL"] = self._h_usetmaxnre_dec

        # ---- Stutter (advance PC only, no state change) ----
        for m in ("WARPSYNC", "WARPSYNC.ALL"):
            h[m] = self._h_stutter

        # EXIT / BRA / RET / CALL.REL.NOINC are terminators handled by
        # _encode_block, not the handler table.

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def generate(
        self,
        cfg: CFG,
        name: str,
        regPerThread: int,
        n_warps: int = 1,
        gridDim: Tuple[int, int, int] = (1, 1, 1),
        blockDim: Tuple[int, int, int] = (1, 1, 1),
    ) -> TLASassProcess:
        """
        Lift ``cfg`` into a TLASassProcess named ``name``.

        The CFG must represent exactly one kernel function (as returned by
        cfg.build_cfgs()).  For multi-kernel files, call generate() once per
        kernel.

        Parameters
        ----------
        cfg      : sliced or unsliced single-kernel CFG
        name     : TLA+ module name
        n_warps  : number of warp threads to model (default 1)
        """
        regs_zero, regs_false, regs_true = self._collect_registers(cfg)
        used_regs = set(regs_zero) | set(regs_false) | set(regs_true)
        print(
            f"[codegen] registers in sliced CFG: {len(used_regs)} (was 410 hardcoded)",
            flush=True,
        )

        proc = TLASassProcess(name, gridDim, blockDim, regPerThread, apalache_compatible=True)
        # proc.used_regs = used_regs
        proc.initialize()

        self._sr_constants: dict[str, Constant] = {}
        self._sr_proc = proc

        # Encode CFG once with the template thread
        template = proc.template_thread

        assert template is not None
        
        self._encode_cfg(template, cfg)

        return proc

    # ------------------------------------------------------------------
    # Register discovery
    # ------------------------------------------------------------------

    def _collect_registers(self, cfg: CFG) -> tuple[list[str], list[str], list[str]]:
        """Return (regs_zero, regs_false, regs_true)."""
        seen: set[str] = set()
        discard_written: set[str] = set()
        _pred_re = re.compile(r"^U?P\d+$")
        for bb in cfg.blocks:
            for instr in bb.instructions:
                if instr.predicate and instr.predicate.name not in _ALWAYS_TRUE_PREDS:
                    seen.add(instr.predicate.name)
                for r in defs_of(instr):
                    if r in _ALWAYS_TRUE_PREDS:
                        discard_written.add(r)
                    elif r not in _ZERO_REGS and not r.startswith("SR_"):
                        seen.add(r)
                for r in uses_of(instr):
                    if r not in _DISCARD_DSTS and not r.startswith("SR_"):
                        seen.add(r)

        def _key(name: str) -> tuple[int, int]:
            m = re.match(r"([A-Za-z]+)(\d+)$", name)
            order = {"R": 0, "UR": 1, "P": 2, "UP": 3}
            if m:
                return (order.get(m.group(1), 9), int(m.group(2)))
            return (9, 0)

        regs_zero = sorted([r for r in seen if not _pred_re.match(r)], key=_key)
        regs_false = sorted([r for r in seen if _pred_re.match(r)], key=_key)
        return regs_zero, regs_false, sorted(discard_written, key=_key)

    # ------------------------------------------------------------------
    # CFG -> TLA+ encoding
    # ------------------------------------------------------------------

    def _encode_cfg(self, thread: TLASassThread, cfg: CFG) -> None:
        if not cfg.blocks:
            return
        block_states: dict[int, str] = {}
        for bb in cfg.blocks:
            if bb.id == 0:
                block_states[bb.id] = thread._currentState()
            else:
                label = (
                    "_" + bb.entry_labels[0].replace(".", "_")
                    if bb.entry_labels
                    else ""
                )
                block_states[bb.id] = thread.allocateState(f"bb_{bb.id}{label}")
        for bb in cfg.blocks:
            self._encode_block(thread, bb, block_states)

    def _encode_block(
        self,
        thread: TLASassThread,
        bb: BasicBlock,
        block_states: dict[int, str],
    ) -> None:
        thread.setState(block_states[bb.id])
        instrs = bb.instructions
        for instr in instrs[:-1]:
            self._emit_instruction(thread, instr)
        if not instrs:
            if bb.successors:
                self._emit_goto(thread, block_states[bb.successors[0].id])
            return

        last = instrs[-1]

        if bb.terminator_kind == TerminatorKind.EXIT:
            thread.stopInstruction()

        elif bb.terminator_kind == TerminatorKind.FALL_THROUGH:
            self._emit_instruction(thread, last)
            if bb.successors:
                self._emit_goto(thread, block_states[bb.successors[0].id])

        elif bb.terminator_kind == TerminatorKind.UNCONDITIONAL:
            if bb.successors:
                self._emit_goto(thread, block_states[bb.successors[0].id])

        elif bb.terminator_kind == TerminatorKind.CONDITIONAL:
            pred = self._branch_pred(thread, last)
            taken = (
                block_states[bb.successors[0].id] if len(bb.successors) > 0 else None
            )
            fall = block_states[bb.successors[1].id] if len(bb.successors) > 1 else None
            if pred is not None and taken and fall:
                thread.appendBranchInstruction(pred, taken, fall)
            elif taken:
                self._emit_goto(thread, taken)

        elif bb.terminator_kind == TerminatorKind.INDIRECT:
            if bb.successors:
                self._emit_indirect_branch(thread, bb, block_states)
            else:
                self.log.append(
                    f"INDIRECT BRANCH at /*{last.address_str}*/ {last.mnemonic}: "
                    f"targets unknown -- treating block as EXIT"
                )
                thread.stopInstruction()

    def _emit_goto(self, thread: TLASassThread, target_state: str) -> None:
        current = thread._currentState()
        pc_trans = thread.pcTransition(current, target_state)
        unchanged_vars = thread._unchangedExcept([thread.process.getPcMap()])
        expr = (pc_trans & Unchanged(unchanged_vars)) if unchanged_vars else pc_trans
        safe = re.sub(r"[^a-zA-Z0-9]", "_", current)
        defn_name = f"goto_{safe}"
        defn = thread.process.createDefinition(defn_name, expr, params=[thread.t_param])
        thread.thread_definitions.append(defn)

    def _emit_indirect_branch(
        self,
        thread: TLASassThread,
        bb: BasicBlock,
        block_states: dict[int, str],
    ) -> None:
        """Emit a nondeterministic branch (BRX) as a disjunction of gotos."""
        current = thread._currentState()
        unchanged_vars = thread._unchangedExcept([thread.process.getPcMap()])
        gotos = []
        for succ in bb.successors:
            target = block_states[succ.id]
            pc_trans = thread.pcTransition(current, target)
            gotos.append(pc_trans)
        expr = Or(*gotos) if len(gotos) > 1 else gotos[0]
        if unchanged_vars:
            expr = expr & Unchanged(unchanged_vars)
        safe = re.sub(r"[^a-zA-Z0-9]", "_", current)
        defn_name = f"brx_{safe}"
        defn = thread.process.createDefinition(defn_name, expr, params=[thread.t_param])
        thread.thread_definitions.append(defn)

    def _emit_instruction(self, thread: TLASassThread, instr: Instruction) -> None:
        mnem = instr.mnemonic
        handler = self._handlers.get(mnem)
        if handler is None:
            stem = mnem.split(".")[0]
            handler = self._handlers.get(stem)
        if handler is None:
            self.log.append(
                f"UNSUPPORTED /*{instr.address_str}*/  {mnem}"
                + (f"  pred={instr.predicate}" if instr.predicate else "")
                + f"  ops=[{', '.join(str(o) for o in instr.operands)}]"
            )
            return
        handler(thread, instr)

    # ------------------------------------------------------------------
    # Operand helpers
    # ------------------------------------------------------------------

    def _op_expr(self, thread: TLASassThread, op) -> Expr:
        if isinstance(op, RegisterOp):
            if op.name in _ZERO_REGS:
                return Literal(0)
            if op.name in _ALWAYS_TRUE_PREDS:
                return Literal(True)
            if op.name.startswith("SR_"):
                return self._sr_constant(op.name)
            expr = thread.getRegister(op.name)
            if "neg" in op.modifiers:
                if self._PRED_RE.match(op.name):
                    expr = Not(expr)   # boolean negation for predicates (!P0)
                else:
                    expr = Neg(expr)   # arithmetic negation for registers (-R4)
            return expr
        if isinstance(op, ImmediateOp):
            if isinstance(op.value, int):
                return Literal(op.value)
            return Literal(0)
        if isinstance(op, ConstBankOp):
            offset_str = op.offset.strip()
            if re.match(r"^[A-Za-z]", offset_str):
                m = re.match(r"^([A-Za-z]\w*)([+\-](?:0x[\da-fA-F]+|\d+))?", offset_str)
                if m:
                    base_expr = thread.getRegister(m.group(1))
                    if m.group(2):
                        offset_expr = base_expr + Literal(int(m.group(2), 0))
                    else:
                        offset_expr = base_expr
                else:
                    offset_expr = Literal(0)
            else:
                try:
                    offset_expr = Literal(int(offset_str, 0))
                except ValueError:
                    offset_expr = Literal(0)
            return thread.process.mem[offset_expr]
        if isinstance(op, MemAddrOp):
            return self._mem_addr_expr(thread, op)
        if isinstance(op, LabelRef):
            return Literal(op.name)
        return Literal(0)

    def _mem_addr_expr(self, thread: TLASassThread, op: MemAddrOp) -> Expr:
        terms: list[Expr] = []
        for part in op.parts:
            part = part.strip()
            if not part:
                continue
            if re.match(r"^[A-Za-z]", part):
                base = part.split(".")[0]
                if base not in _ZERO_REGS:
                    terms.append(thread.getRegister(base))
            else:
                try:
                    terms.append(Literal(int(part, 0)))
                except ValueError:
                    pass
        if not terms:
            return Literal(0)
        if len(terms) == 1:
            return terms[0]
        return Add(*terms)

    def _dst(self, instr: Instruction, idx: int = 0) -> str:
        op = instr.operands[idx]
        return op.name if isinstance(op, RegisterOp) else "RZ"

    def _src(self, thread: TLASassThread, instr: Instruction, idx: int) -> Expr:
        return self._op_expr(thread, instr.operands[idx])

    _PRED_RE = re.compile(r"^U?P\d+$")

    def _coerce_bool(self, expr: Expr, operand) -> Expr:
        if isinstance(operand, RegisterOp) and self._PRED_RE.match(operand.name):
            return expr
        if isinstance(expr, Literal) and isinstance(expr.value, bool):
            return expr
        if isinstance(expr, Literal) and isinstance(expr.value, int):
            return Literal(expr.value != 0)
        return expr != Literal(0)

    def _pred_expr(self, thread: TLASassThread, instr: Instruction) -> Optional[Expr]:
        p = instr.predicate
        if p is None or p.name in _ALWAYS_TRUE_PREDS:
            return None
        expr = thread.getRegister(p.name)
        if p.negated:
            expr = Not(expr)
        return expr

    def _branch_pred(self, thread: TLASassThread, instr: Instruction) -> Optional[Expr]:
        if instr.predicate and instr.predicate.name not in _ALWAYS_TRUE_PREDS:
            return self._pred_expr(thread, instr)
        for op in instr.operands:
            if isinstance(op, LabelRef):
                break
            if isinstance(op, RegisterOp):
                name = op.name
                is_pred = (name.startswith("UP") and name[2:].isdigit()) or (
                    name.startswith("P") and name[1:].isdigit()
                )
                if is_pred and name not in _ALWAYS_TRUE_PREDS:
                    expr = thread.getRegister(name)
                    if "neg" in op.modifiers:
                        expr = Not(expr)
                    return expr
        return None

    # ------------------------------------------------------------------
    # Write helpers
    # ------------------------------------------------------------------

    def _write_reg(
        self, thread: TLASassThread, instr: Instruction, dst: str, value: Expr
    ) -> None:
        if dst in _DISCARD_DSTS:
            name = instr.mnemonic.lower().replace(".", "_")
            noop = thread._createUnchangedExceptExpr(
                Literal(True), [thread.process.getPcMap()]
            )
            thread.appendInstruction(name, noop)
            return
        pred = self._pred_expr(thread, instr)
        if pred is not None:
            value = IfThenElse(pred, value, thread.getRegister(dst))
        thread.appendRegisterInstruction(
            instr.mnemonic.lower().replace(".", "_"), dst, value
        )

    def _emit_dual(
        self,
        thread: TLASassThread,
        instr: Instruction,
        dst0: str,
        val0: Expr,
        dst1: str,
        val1: Expr,
    ) -> None:
        name = instr.mnemonic.lower().replace(".", "_")
        d0_ok = dst0 not in _DISCARD_DSTS
        d1_ok = dst1 not in _DISCARD_DSTS
        if d0_ok and d1_ok:
            thread._append_dual_reg_instr(name, dst0, val0, dst1, val1)
        elif d0_ok:
            thread.appendRegisterInstruction(name, dst0, val0)
        elif d1_ok:
            thread.appendRegisterInstruction(name, dst1, val1)
        else:
            thread._stutter(name)

    def _const_bank_raw_addr(
        self, thread: TLASassThread, instr: Instruction, idx: int
    ) -> Expr:
        op = instr.operands[idx]
        if isinstance(op, ConstBankOp):
            offset_str = op.offset.strip()
            if re.match(r"^[A-Za-z]", offset_str):
                m = re.match(r"^([A-Za-z]\w*)([+\-](?:0x[\da-fA-F]+|\d+))?", offset_str)
                if m:
                    base_expr = thread.getRegister(m.group(1))
                    if m.group(2):
                        return base_expr + Literal(int(m.group(2), 0))
                    return base_expr
            else:
                try:
                    return Literal(int(offset_str, 0))
                except ValueError:
                    pass
        return Literal(0)

    def _sr_constant(self, sr_name: str) -> Constant:
        tla_name = sr_name.replace(".", "_")
        if tla_name not in self._sr_constants:
            self._sr_constants[tla_name] = self._sr_proc.createConstant(tla_name)
        return self._sr_constants[tla_name]

    # ==================================================================
    # Instruction handlers  (one per sass_insns.h macro)
    # ==================================================================

    # ---- S2R / S2UR / MOV / UMOV / CS2R / R2UR:  dst = src ----

    def _h_mov(self, thread: TLASassThread, instr: Instruction) -> None:
        self._write_reg(thread, instr, self._dst(instr, 0), self._src(thread, instr, 1))

    # ---- UP2UR:  uniform predicate to uniform register (bitmask pack) ----

    def _h_up2ur(self, thread: TLASassThread, instr: Instruction) -> None:
        # UP2UR UR5, UPR, URZ, 0x2 — packs selected predicates into UR.
        # Modelled as dst = imm (opaque data dependency on predicate state).
        dst = self._dst(instr, 0)
        imm = self._src(thread, instr, 3)
        self._write_reg(thread, instr, dst, imm)

    # ---- IABS:  dst = |src| ----

    def _h_iabs(self, thread: TLASassThread, instr: Instruction) -> None:
        self._write_reg(thread, instr, self._dst(instr, 0), Abs(self._src(thread, instr, 1)))

    # ---- I2F.RP / MUFU.RCP / F2I:  float ops (data-dep only) ----

    def _h_fp_passthrough(self, t: TLASassThread, i: Instruction) -> None:
        self._write_reg(t, i, self._dst(i, 0), self._src(t, i, 1))

    # ---- IADD3:  dst = s1 + s2 + s3 ----

    def _h_iadd3(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        val = self._src(thread, instr, 1) + self._src(thread, instr, 2) + self._src(thread, instr, 3)
        self._write_reg(thread, instr, dst, val)

    # ---- IMAD:  dst = s1 * s2 + s3 ----

    def _h_imad(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        val = self._src(thread, instr, 1) * self._src(thread, instr, 2) + self._src(thread, instr, 3)
        self._write_reg(thread, instr, dst, val)

    # ---- IMAD.HI.U32:  dst = ((s1*s2) + (dst<<32 | s3)) >> 32 ----

    def _h_imad_hi_u32(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        s1 = self._src(thread, instr, 1)
        s2 = self._src(thread, instr, 2)
        s3 = self._src(thread, instr, 3)
        dst_cur = thread.getRegister(dst)
        full = s1 * s2 + ((dst_cur << Literal(32)) + s3)
        self._write_reg(thread, instr, dst, full >> Literal(32))

    # ---- IMNMX.U32:  dst = mnpred ? min(s1,s2) : max(s1,s2) ----

    def _h_imnmx_u32(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        s1 = self._src(thread, instr, 1)
        s2 = self._src(thread, instr, 2)
        mnpred = self._src(thread, instr, 3)
        self._write_reg(
            thread, instr, dst, IfThenElse(mnpred, Min(s1, s2), Max(s1, s2))
        )

    # ---- VIADD:  dst = s1 + s2 ----

    def _h_viadd(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        val = self._src(thread, instr, 1) + self._src(thread, instr, 2)
        self._write_reg(thread, instr, dst, val)

    # ---- VIADDMNMX:  dst = pred ? min(s1+imm, s2) : max(s1+imm, s2) ----

    def _h_viaddmnmx(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        s1 = self._src(thread, instr, 1)
        s2 = self._src(thread, instr, 2)
        imm = self._src(thread, instr, 3)
        mnpred = self._src(thread, instr, 4)
        val = IfThenElse(mnpred, Min(s1 + imm, s2), Max(s1 + imm, s2))
        self._write_reg(thread, instr, dst, val)

    # ---- VIMNMX:  dst = pred ? min(s1, s2) : max(s1, s2) ----

    def _h_vimnmx(self, thread: TLASassThread, instr: Instruction) -> None:
        # 6 operands: dst, pdst0, pdst1, src1, src2, pred
        dst = self._dst(instr, 0)
        pdst0 = self._dst(instr, 1)
        pdst1 = self._dst(instr, 2)
        s1 = self._src(thread, instr, 3)
        s2 = self._src(thread, instr, 4)
        mnpred = self._src(thread, instr, 5)
        result = IfThenElse(mnpred, Min(s1, s2), Max(s1, s2))
        cmp = s1 < s2
        not_cmp = Not(cmp)
        # dst + two predicate outputs
        name = instr.mnemonic.lower().replace(".", "_")
        d0_ok = dst not in _DISCARD_DSTS
        p0_ok = pdst0 not in _DISCARD_DSTS
        p1_ok = pdst1 not in _DISCARD_DSTS
        writes = []
        if d0_ok:
            writes.append((dst, result))
        if p0_ok:
            writes.append((pdst0, cmp))
        if p1_ok:
            writes.append((pdst1, not_cmp))
        if len(writes) >= 2:
            thread._append_multi_reg_instr(name, writes)
        elif len(writes) == 1:
            thread.appendRegisterInstruction(name, writes[0][0], writes[0][1])
        else:
            thread._stutter(name)

    # ---- SHF.R.U32.HI:  dst = upper32(concat(hi,lo) >> rot) ----

    def _h_shf_r_u32_hi(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        s1 = self._src(thread, instr, 1)  # lo
        rot = self._src(thread, instr, 2)  # shift
        s2 = self._src(thread, instr, 3)  # hi
        self._write_reg(thread, instr, dst, FunnelShr(s2, s1, rot))

    # ---- SHF.R.S32.HI:  same TLA+ model as unsigned ----

    def _h_shf_r_s32_hi(self, thread: TLASassThread, instr: Instruction) -> None:
        self._h_shf_r_u32_hi(thread, instr)

    # ---- SHF.L.U32:  dst = upper32(concat(hi,lo) << rot) ----

    def _h_shf_l_u32(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        lo = self._src(thread, instr, 1)
        rot = self._src(thread, instr, 2)
        hi = self._src(thread, instr, 3)
        concat = (hi << Literal(32)) + lo
        self._write_reg(thread, instr, dst, (concat << rot) >> Literal(32))

    # ---- LOP3.LUT:  dst = logical_op3(s1, s2, s3, lut) ----

    def _h_lop3_lut(self, thread: TLASassThread, instr: Instruction) -> None:
        # 5-operand form only (per sass_insns.h LOP3_LUT)
        n = len(instr.operands)
        if n >= 7:
            # 7-operand form: dual dest (treated like PLOP3)
            dst0 = self._dst(instr, 0)
            dst1 = self._dst(instr, 1)
            s1 = self._coerce_bool(self._src(thread, instr, 2), instr.operands[2])
            s2 = self._coerce_bool(self._src(thread, instr, 3), instr.operands[3])
            s3 = self._src(thread, instr, 4)
            lut = self._src(thread, instr, 5)
            result = IfThenElse(s1, IfThenElse(s2, s3, lut), IfThenElse(s2, lut, s3))
            self._emit_dual(thread, instr, dst0, result, dst1, result)
        else:
            dst = self._dst(instr, 0)
            s1 = self._coerce_bool(self._src(thread, instr, 1), instr.operands[1])
            s2 = self._coerce_bool(self._src(thread, instr, 2), instr.operands[2])
            s3 = self._src(thread, instr, 3)
            lut = self._src(thread, instr, 4)
            result = IfThenElse(s1, IfThenElse(s2, s3, lut), IfThenElse(s2, lut, s3))
            self._write_reg(thread, instr, dst, result)

    # ---- PLOP3.LUT:  dst1 = logical_op3(s1, s2, s3, lut) ----

    def _h_plop3_lut(self, thread: TLASassThread, instr: Instruction) -> None:
        dst0 = self._dst(instr, 0)
        dst1 = self._dst(instr, 1)
        s1 = self._src(thread, instr, 2)
        s2 = self._src(thread, instr, 3)
        s3 = self._src(thread, instr, 4)
        lut = self._src(thread, instr, 5)
        s4 = self._src(thread, instr, 6)
        result = IfThenElse(s1, IfThenElse(s2, s3, lut), IfThenElse(s2, lut, s4))
        not_result = Not(result)
        self._emit_dual(thread, instr, dst0, result, dst1, not_result)

    # ---- SEL:  dst = pred ? s1 : s2 ----

    def _h_sel(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        s1 = self._src(thread, instr, 1)
        s2 = self._src(thread, instr, 2)
        pred = self._src(thread, instr, 3)
        self._write_reg(thread, instr, dst, IfThenElse(pred, s1, s2))

    # ---- LEA:  dst = (src << imm_shift) + b ----

    def _h_lea(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        src = self._src(thread, instr, 1)
        b = self._src(thread, instr, 2)
        imm_shift = self._src(thread, instr, 3)
        self._write_reg(thread, instr, dst, (src << imm_shift) + b)

    # ---- LEA.HI:  dst = ((concat(ahi,alo) << imm_shift) >> 32) + b ----

    def _h_lea_hi(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr, 0)
        alo = self._src(thread, instr, 1)
        b = self._src(thread, instr, 2)
        ahi = self._src(thread, instr, 3)
        imm_shift = self._src(thread, instr, 4)
        concat = (ahi << Literal(32)) + alo
        upper = (concat << imm_shift) >> Literal(32)
        self._write_reg(thread, instr, dst, upper + b)

    @staticmethod
    def _usetmaxreg_count_op(instr: Instruction, idx: int):
        """Return the integer register count from operand at idx."""
        op = instr.operands[idx]
        if isinstance(op, ImmediateOp):
            return op.value
        if isinstance(op, RegisterOp):
            return op.name
        return None

    def _h_usetmaxnre_inc(self, thread: TLASassThread, instr: Instruction) -> None:
        # TRY_ALLOC: UP0, 0xd0  — operand 0 is predicate output, operand 1 is count
        absReg = self._src(thread, instr, 1)
        thread.emit_usetmaxreg(absReg, self._usetmaxreg_count_op(instr, 1), is_inc=True)

    def _h_usetmaxnre_dec(self, thread: TLASassThread, instr: Instruction) -> None:
        # DEALLOC: 0x40  — operand 0 is count
        absReg = self._src(thread, instr, 0)
        thread.emit_usetmaxreg(absReg, self._usetmaxreg_count_op(instr, 0), is_inc=False)

    # ---- LEA.HI.SX32:  sign-extended variant (ahi = sign-ext of alo) ----

    def _h_lea_hi_sx32(self, thread: TLASassThread, instr: Instruction) -> None:
        dst = self._dst(instr)
        alo = self._src(thread, instr, 1)
        b = self._src(thread, instr, 2)
        imm_shift = self._src(thread, instr, 3)
        upper = (alo << imm_shift) >> Literal(32)
        self._write_reg(thread, instr, dst, upper + b)

    # ---- ISETP variants:  dst0 = cond, dst1 = ~cond ----

    def _h_isetp_cond(self, t: TLASassThread, i: Instruction, condition: Expr) -> None:
        not_cond = Not(condition)
        self._emit_dual(t, i, self._dst(i, 0), condition, self._dst(i, 1), not_cond)

    def _h_isetp_lt_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) < self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_gt_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) > self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_ge_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) >= self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_ne_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) != self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_eq_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) == self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_le_and(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) <= self._src(t, i, 3)) & self._src(t, i, 4)
        )

    def _h_isetp_ge_or(self, t: TLASassThread, i: Instruction):
        self._h_isetp_cond(
            t, i, (self._src(t, i, 2) >= self._src(t, i, 3)) | self._src(t, i, 4)
        )

    def _h_p2r(self, t: TLASassThread, i: Instruction):
        self._write_reg(t, i, self._dst(i, 0), self._src(t, i, 1))

    # ---- ULDC:  dst = src  (constant bank load) ----

    def _h_uldc(self, t: TLASassThread, i: Instruction):
        self._write_reg(t, i, self._dst(i, 0), self._src(t, i, 1))

    # ---- ULDC.64:  two-register constant bank load ----

    def _h_uldc_64(self, t: TLASassThread, i: Instruction):
        t.emit_uldc_64(self._dst(i, 0), self._const_bank_raw_addr(t, i, 1))

    # ---- SYNCS.PHASECHK:  set predicate dest to TRUE ----

    def _h_syncs_phasechk(self, t: TLASassThread, i: Instruction):
        self._write_reg(t, i, self._dst(i, 0), Literal(True))

    # ---- Stutter (PC advances, nothing else changes) ----

    def _h_stutter(self, t: TLASassThread, i: Instruction):
        name = i.mnemonic.lower().replace(".", "_")
        noop = t._createUnchangedExceptExpr(Literal(True), [t.process.getPcMap()])
        t.appendInstruction(name, noop)
